name: Build (fx-cg)

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    # Run all steps inside your GHCR image
    container:
      image: ghcr.io/therainbowphoenix/gint-docker:main

    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Build (fxsdk build-cg)
        run: |
          fxsdk build-cg

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: fxcg-apps
          path: |
            *.hh3
            *.g1a
            *.g3a
          if-no-files-found: error
          retention-days: 14
